# ESPHome configuration -- https://esphome.io/

packages:
  board: !include {
    file: common/shelly-2pm-gen4.yaml,
    vars: { name_1: "${name_1}", name_2: "${name_2}" }
  }
  base: !include common/base.yaml
  thread: !include common/thread.yaml
  lights: !include {
    file: common/light-dual.yaml,
    vars: { name_1: "${name_1}", name_2: "${name_2}" }
  }

substitutions:
  name_1: Licht Esszimmer
  name_2: Licht Wohnzimmer

esphome:
  name: licht-esszimmer
  friendly_name: Licht Esszimmer
  area: Esszimmer
