# ESPHome configuration -- https://esphome.io/

packages:
  board: !include {
    file: common/shelly-1pm-gen4.yaml,
    vars: { name: "${name}" }
  }
  base: !include common/base.yaml
  thread: !include common/thread.yaml
  light: !include {
    file: common/light.yaml,
    vars: { name: "${name}", timeout: "${timeout}" }
  }

substitutions:
  name: Licht Treppenhaus EG
  timeout: 5min

esphome:
  name: licht-treppenhaus-eg
  friendly_name: Licht Treppenhaus EG
  area: Esszimmer
