# ESPHome configuration -- https://esphome.io/

packages:
  board: !include {
    file: common/shelly-2pm-gen4.yaml,
    vars: { name_1: "${name_1}", name_2: "${name_2}" }
  }
  base: !include common/base.yaml
  thread: !include common/thread.yaml
  light_1: !include {
    file: common/light.yaml,
    vars: { name: "${name_1}", suffix: _1, timeout: "${timeout_1}" }
  }
  light_2: !include {
    file: common/light.yaml,
    vars: { name: "${name_2}", suffix: _2, timeout: "${timeout_2}" }
  }

substitutions:
  name_1: Licht Eingang
  name_2: Licht Aussen
  timeout_1: 5min
  timeout_2: 5min

esphome:
  name: licht-eingang
  friendly_name: Licht Eingang
  area: Eingang
