# ESPHome configuration package -- https://esphome.io/components/packages/
# for Shelly 1PM Gen4 devices -- https://kb.shelly.cloud/knowledge-base/shelly-1pm-gen4

# Known GPIOs:
# - GPIO1: Button (active low)
# - GPIO3: NTC Temperature sensor
# - GPIO4: Relay (active high)
# - GPIO6: BL0942 Tx
# - GPIO7: BL0942 Rx
# - GPIO8: strapping pin, pulled up
# - GPIO9: BOOT0 (Header Pin 6, active low)
# - GPIO10: Switch (active high)
# - GPIO11: LED (active low)
# - GPIO12: ESP_DBG_UART (Header Pin 1, normally USB_D-)
# - GPIO15: strapping pin, pulled low
# - GPIO16: U0TXD (Header Pin 2)
# - GPIO17: U0RXD (Header Pin 3)
#
# Unknown/unused GPIOs:
# - GPIO0: (~0.7V when off, ~1.3V when on)
# - GPIO2: (high)
# - GPIO5: (low)
# - GPIO13: (low, normally USB_D+)
# - GPIO14: (low)
# - GPIO18: (low)
# - GPIO19: (low, high on 2PM)
# - GPIO20: (low)
# - GPIO21: (low)
# - GPIO22: (low)
# - GPIO23: (low)

defaults:
  # Max current (A) to allow on output. Higher current will trip the protection.
  max_current: 16.0
  # Max temperature (°C) to allow. Higher temperature will trip the protection.
  max_temperature: 80.0

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

logger:
  # ESP32-C6 uses USB CDC for logging by default, but Shelly devices don't have USB
  hardware_uart: UART0

uart:
  baud_rate: 9600
  tx_pin: GPIO6
  rx_pin:
    number: GPIO7
    mode:
      input: true
      pullup: true
  id: uart_bl0942

status_led:
  pin:
    number: GPIO11
    inverted: true

sensor:
  # Internal NTC temperature sensor
  - platform: adc
    pin: GPIO3
    # Short update interval for quick detection of overheating
    update_interval: 1s
    id: sensor_ntc_adc
  - platform: resistance
    sensor: sensor_ntc_adc
    configuration: DOWNSTREAM
    resistor: 10kOhm
    id: sensor_ntc_resistance
  - platform: ntc
    sensor: sensor_ntc_resistance
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K # 25°C
    id: sensor_ntc_temperature
    on_value_range:
      - above: ${max_temperature}
        then:
          - output.turn_off: relay_1
          - logger.log:
              format: "OVERHEAT DETECTED, turned off output"
              level: WARN
          - homeassistant.action:
              action: notify.persistent_notification
              data:
                title: "OVERHEAT ${name}"
                message: "Shelly 1PM has overheated and turned off the output to protect itself."

  # Change internal temperature sensor (which seems uncalibrated on Shelly
  # devices) to use NTC temperature but update less often
  - id: !extend sensor_internal_temperature
    platform: copy
    source_id: sensor_ntc_temperature
    filters:
      - throttle_average: 60s

  # Energy sensor
  - platform: bl0942
    voltage:
      id: sensor_voltage
      icon: mdi:sine-wave
    current:
      id: sensor_current
      icon: mdi:current-ac
      on_value_range:
        - above: ${max_current}
          then:
            - output.turn_off: relay_1
            - logger.log:
                format: "OVERCURRENT DETECTED, turned off output"
                level: WARN
            - homeassistant.action:
                action: notify.persistent_notification
                data:
                  title: "OVERCURRENT ${name}"
                  message: "Shelly 1PM was overloaded and turned off the output to protect itself."
    power:
      id: sensor_power
      icon: mdi:flash
    energy:
      id: sensor_energy
      icon: mdi:meter-electric-outline
    frequency:
      id: sensor_frequency
      icon: mdi:sine-wave
      accuracy_decimals: 2
    # Short update interval for quick detection of overload
    update_interval: 1s
    uart_id: uart_bl0942
    line_frequency: 50Hz
    id: sensor_bl0942

  # Publish energy sensor values, but less often to reduce traffic
  - platform: copy
    source_id: sensor_voltage
    name: Voltage
    filters:
      - throttle_average: 10s
    state_topic: null
  - platform: copy
    source_id: sensor_current
    name: Current
    filters:
      - throttle_average: 10s
    state_topic: null
  - platform: copy
    source_id: sensor_power
    name: Power
    filters:
      - throttle_average: 10s
  - platform: copy
    source_id: sensor_energy
    name: Energy
    filters:
      - throttle_average: 10s
    state_topic: null
  - platform: copy
    source_id: sensor_frequency
    name: Frequency
    filters:
      - throttle_average: 10s
    state_topic: null

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    id: internal_button
    filters:
      - delayed_on_off: 10ms
    entity_category: diagnostic
  - platform: gpio
    pin: GPIO10
    id: switch_1
    filters:
      - delayed_on_off: 50ms

output:
  - platform: gpio
    id: relay_1
    pin: GPIO4
