# ESPHome configuration package -- https://esphome.io/components/packages/
# for Shelly 2PM Gen4 devices -- https://kb.shelly.cloud/knowledge-base/shelly-2pm-gen4

# Known GPIOs:
# - GPIO1: ESP_DBG_UART (Header Pin 1)
# - GPIO3: Relay 2 (active high)
# - GPIO4: NTC Temperature sensor
# - GPIO5: Relay 1 (active high)
# - GPIO6: I2C SDA
# - GPIO7: I2C SCL
# - GPIO8: strapping pin, pulled up
# - GPIO9: BOOT0 (Header Pin 6, active low)
# - GPIO10: Switch 2 (active high)
# - GPIO11: Switch 1 (active high)
# - GPIO12: Button (active low, normally USB_D-)
# - GPIO15: strapping pin, pulled low
# - GPIO16: U0TXD (Header Pin 2)
# - GPIO17: U0RXD (Header Pin 3)
# - GPIO18: LED (active low)
#
# Unknown/unused GPIOs:
# - GPIO0: (low)
# - GPIO2: (high)
# - GPIO13: (low, normally USB_D+)
# - GPIO14: (low)
# - GPIO19: (high)
# - GPIO20: (low)
# - GPIO21: (low)
# - GPIO22: (low)
# - GPIO23: (low)
#
# TODO: Are ADE7953 IRQ and RST connected to GPIOs like in Gen3?

defaults:
  # Name prefix of channel A sensors
  name_1: Channel A
  # Name prefix of channel B sensors
  name_2: Channel B
  # Max current (A) to allow per output. Higher current will trip the protection.
  max_current: 10.0
  # Max temperature (°C) to allow. Higher temperature will trip the protection.
  max_temperature: 80.0

esp32:
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf

logger:
  # ESP32-C6 uses USB CDC for logging by default, but Shelly devices don't have USB
  hardware_uart: UART0

i2c:
  sda: GPIO6
  scl: GPIO7

status_led:
  pin:
    number: GPIO18
    inverted: true

sensor:
  # Internal NTC temperature sensor
  - platform: adc
    pin: GPIO4
    update_interval: 10s
    id: sensor_ntc_adc
  - platform: resistance
    sensor: sensor_ntc_adc
    configuration: DOWNSTREAM
    resistor: 10kOhm
    id: sensor_ntc_resistance
  # Change internal temperature sensor to use NTC temperature sensor
  - id: !extend sensor_internal_temperature
    platform: ntc
    sensor: sensor_ntc_resistance
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K # 25°C
    on_value_range:
      - above: ${max_temperature}
        then:
          - output.turn_off: relay_1
          - output.turn_off: relay_2
          - logger.log:
              format: "OVERHEAT DETECTED, turned off all outputs"
              level: WARN

  - platform: ade7953_i2c
    voltage:
      id: sensor_voltage
      name: Voltage
      icon: mdi:sine-wave
      state_topic: null
    frequency:
      id: sensor_frequency
      name: Frequency
      icon: mdi:sine-wave
      state_topic: null
    current_a:
      id: sensor_current_1
      name: ${name_1} Current
      icon: mdi:current-ac
      on_value_range:
        - above: ${max_current}
          then:
            - output.turn_off: relay_1
            - logger.log:
                format: "OVERCURRENT DETECTED, turned off output 1"
                level: WARN
      state_topic: null
    current_b:
      id: sensor_current_2
      name: ${name_2} Current
      icon: mdi:current-ac
      on_value_range:
        - above: ${max_current}
          then:
            - output.turn_off: relay_2
            - logger.log:
                format: "OVERCURRENT DETECTED, turned off output 2"
                level: WARN
      state_topic: null
    power_factor_a:
      name: ${name_1} Power Factor
      icon: mdi:percent-outline
      state_topic: null
    power_factor_b:
      name: ${name_2} Power Factor
      icon: mdi:percent-outline
      state_topic: null
    apparent_power_a:
      name: ${name_1} Apparent Power
      icon: mdi:flash
      state_topic: null
    apparent_power_b:
      name: ${name_2} Apparent Power
      icon: mdi:flash
      state_topic: null
    active_power_a:
      id: sensor_power_1
      name: ${name_1} Power
      icon: mdi:flash
      filters:
        - multiply: -1
    active_power_b:
      id: sensor_power_2
      name: ${name_2} Power
      icon: mdi:flash
      filters:
        - multiply: -1
    reactive_power_a:
      name: ${name_1} Reactive Power
      icon: mdi:flash
      state_topic: null
    reactive_power_b:
      name: ${name_2} Reactive Power
      icon: mdi:flash
      state_topic: null
    current_pga_gain_a: 4x
    current_pga_gain_b: 4x
    update_interval: 10s
    use_accumulated_energy_registers: true
    id: sensor_ade7953

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
    id: internal_button
    filters:
      - delayed_on_off: 10ms
    entity_category: diagnostic
  - platform: gpio
    pin: GPIO11
    id: switch_1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin: GPIO10
    id: switch_2
    filters:
      - delayed_on_off: 50ms

output:
  # Note: for shutters, O1 is typically opening, O2 typically closing
  - platform: gpio
    id: relay_1
    pin: GPIO5
  - platform: gpio
    id: relay_2
    pin: GPIO3
